/*
 * Reeti @ 40 — slide deck content.
 *
 * Edit the array below to change questions, reorder rounds, etc. Each slide
 * is one object. The `type` field decides how it's rendered (see script.js).
 *
 * Types:
 *   title    — opening card
 *   divider  — round opener
 *   mcq      — multiple choice; `answer` is the index into `choices`
 *   tf       — true/false; `answer` is boolean
 *   gag      — the population gag
 *   rapid    — rapid-fire "pick one" personal question
 *   savage   — closing savage question
 *   finale   — closing card
 *
 * Trivia facts were verified via web search (see source URLs). If anything
 * looks wrong, click through to the source before changing the answer.
 */

window.REETI_SLIDES = [
  // ─── Opening ──────────────────────────────────────────────────────
  {
    type: "title",
    kicker: "June 8, 2026 · Happy Birthday",
    q: "Reeti @ 40",
    sub: "40 Questions for 40 Years — Limited Edition since 1986",
  },

  // ─── Round 1: 1986 in the World ───────────────────────────────────
  {
    type: "divider",
    kicker: "Round 1 of 4",
    q: "1986 in the World",
    sub: "Events, politics, disasters, summits.",
  },
  {
    type: "mcq",
    kicker: "Round 1 · 1986 in the World",
    q: "On which date did the Chernobyl nuclear disaster occur?",
    choices: ["March 14, 1986", "April 26, 1986", "May 8, 1986", "June 2, 1986"],
    answer: 1,
    note: "Reactor No. 4 exploded at 01:23 local time near Pripyat, Ukrainian SSR.",
    source: "https://en.wikipedia.org/wiki/Chernobyl_disaster",
  },
  {
    type: "tf",
    kicker: "Round 1 · 1986 in the World",
    q: "The Space Shuttle Challenger broke apart 73 seconds after launch in January 1986.",
    answer: true,
    note: "January 28, 1986. All seven crew killed. Cause: O-ring failure, exacerbated by unusually cold launch temperatures.",
    source: "https://en.wikipedia.org/wiki/Space_Shuttle_Challenger_disaster",
  },
  {
    type: "tf",
    kicker: "Round 1 · 1986 in the World",
    q: "The 1986 appearance of Halley's Comet was the best viewing in 2,000 years.",
    answer: false,
    note: "Actually the WORST viewing in 2,000 years — Earth and the comet were on opposite sides of the Sun near perihelion (Feb 9, 1986).",
    source: "https://en.wikipedia.org/wiki/Halley%27s_Comet",
  },
  {
    type: "mcq",
    kicker: "Round 1 · 1986 in the World",
    q: "Where did Reagan meet Gorbachev for the 1986 superpower summit?",
    choices: ["Geneva", "Reykjavik", "Helsinki", "Vienna"],
    answer: 1,
    note: "October 11–12, 1986. Ended without an agreement but set up the 1987 INF Treaty.",
    source: "https://en.wikipedia.org/wiki/Reykjav%C3%ADk_Summit",
  },
  {
    type: "mcq",
    kicker: "Round 1 · 1986 in the World",
    q: "Which non-violent uprising ousted Ferdinand Marcos in February 1986?",
    choices: [
      "Saffron Revolution",
      "Velvet Revolution",
      "People Power Revolution",
      "Carnation Revolution",
    ],
    answer: 2,
    note: "Feb 22–25, 1986. Corazon Aquino sworn in as President of the Philippines on Feb 25.",
    source: "https://en.wikipedia.org/wiki/People_Power_Revolution",
  },
  {
    type: "mcq",
    kicker: "Round 1 · 1986 in the World",
    q: "Who won the Nobel Peace Prize in 1986?",
    choices: ["Mother Teresa", "Elie Wiesel", "Lech Wałęsa", "Desmond Tutu"],
    answer: 1,
    note: '"For being a messenger to mankind." Announced October 14, 1986.',
    source: "https://www.nobelprize.org/prizes/peace/1986/summary/",
  },
  {
    type: "tf",
    kicker: "Round 1 · 1986 in the World",
    q: "Officially, world population crossed 5 billion in 1986.",
    answer: false,
    note: "The UN designated July 11, 1987 as the Day of Five Billion. (But we know better — Reeti, born June 1986, is why we hit 5B.)",
    source: "https://en.wikipedia.org/wiki/World_population_milestones",
  },
  {
    type: "mcq",
    kicker: "Round 1 · 1986 in the World",
    q: "Which 1986 scandal was first exposed by Lebanese magazine Ash-Shiraa?",
    choices: ["Watergate", "Iran-Contra", "BCCI", "Bofors"],
    answer: 1,
    note: "First exposed November 3, 1986. The Tower Commission was appointed later that month.",
    source: "https://en.wikipedia.org/wiki/Iran%E2%80%93Contra_affair",
  },
  {
    type: "tf",
    kicker: "Round 1 · 1986 in the World",
    q: "The Statue of Liberty celebrated its 100th anniversary in 1986.",
    answer: true,
    note: '"Liberty Weekend," July 3–6, 1986. Reagan rededicated the restored statue; Mitterrand attended.',
    source: "https://en.wikipedia.org/wiki/Liberty_Weekend",
  },
  {
    type: "mcq",
    kicker: "Round 1 · 1986 in the World",
    q: "Which spacecraft made its first (and so far only) flyby of Uranus on January 24, 1986?",
    choices: ["Pioneer 10", "Voyager 1", "Voyager 2", "Galileo"],
    answer: 2,
    note: "Closest approach at 17:59 UT. Discovered 11 new moons and 2 new rings.",
    source: "https://www.nasa.gov/history/35-years-ago-voyager-2-explores-uranus/",
  },

  // ─── Round 2: 1986 in India ───────────────────────────────────────
  {
    type: "divider",
    kicker: "Round 2 of 4",
    q: "1986 in India",
    sub: "Politics, accords, cricket, society.",
  },
  {
    type: "tf",
    kicker: "Round 2 · 1986 in India",
    q: "Rajiv Gandhi was Prime Minister of India throughout 1986.",
    answer: true,
    note: "PM from 31 October 1984 to 2 December 1989 — covers all of 1986.",
    source: "https://en.wikipedia.org/wiki/Rajiv_Gandhi",
  },
  {
    type: "mcq",
    kicker: "Round 2 · 1986 in India",
    q: "The Mizoram Peace Accord of 1986 was signed with which insurgent group?",
    choices: ["ULFA", "NSCN", "MNF (Mizo National Front)", "NDFB"],
    answer: 2,
    note: "Signed June 30, 1986 by Laldenga. Ended a 20-year insurgency.",
    source: "https://en.wikipedia.org/wiki/Mizoram_Peace_Accord",
  },
  {
    type: "mcq",
    kicker: "Round 2 · 1986 in India",
    q: "The Muslim Women (Protection of Rights on Divorce) Act, 1986 was passed in response to which Supreme Court case?",
    choices: ["Kesavananda Bharati", "Shah Bano", "Mandal Commission", "Indira Sawhney"],
    answer: 1,
    note: "Mohd. Ahmed Khan v. Shah Bano Begum (1985). The Act limited a husband's maintenance obligation to the iddat period.",
    source: "https://en.wikipedia.org/wiki/Muslim_Women_(Protection_of_Rights_on_Divorce)_Act_1986",
  },
  {
    type: "tf",
    kicker: "Round 2 · 1986 in India",
    q: "Mizoram became the 23rd state of India in 1986.",
    answer: false,
    note: "The 53rd Constitutional Amendment was passed in 1986, but Mizoram officially became a state on February 20, 1987.",
    source: "https://en.wikipedia.org/wiki/Mizoram",
  },
  {
    type: "mcq",
    kicker: "Round 2 · 1986 in India",
    q: "Who captained India in Test cricket in 1986?",
    choices: ["Sunil Gavaskar", "Mohinder Amarnath", "Kapil Dev", "Dilip Vengsarkar"],
    answer: 2,
    note: "Kapil Dev led India to a famous 2–0 Test series win in England in the summer of 1986.",
    source: "https://en.wikipedia.org/wiki/Kapil_Dev",
  },
  {
    type: "mcq",
    kicker: "Round 2 · 1986 in India",
    q: "The 10th Asian Games (1986) were held in which city?",
    choices: ["Tokyo", "Bangkok", "Seoul", "Beijing"],
    answer: 2,
    note: "September 20 – October 5, 1986. Served as a dry-run for the 1988 Seoul Olympics.",
    source: "https://en.wikipedia.org/wiki/1986_Asian_Games",
  },
  {
    type: "tf",
    kicker: "Round 2 · 1986 in India",
    q: "The Bofors howitzer contract between India and Sweden was signed in 1986.",
    answer: true,
    note: "Contract signed March 1986. The kickback scandal didn't break until Swedish Radio's report on April 16, 1987.",
    source: "https://en.wikipedia.org/wiki/Bofors_scandal",
  },
  {
    type: "mcq",
    kicker: "Round 2 · 1986 in India",
    q: "Who became Mizoram's first Chief Minister after statehood?",
    choices: ["Lalthanhawla", "Laldenga", "T. Sailo", "Zoramthanga"],
    answer: 1,
    note: "Laldenga — the MNF leader who signed the 1986 accord with the Government of India.",
    source: "https://en.wikipedia.org/wiki/Laldenga",
  },
  {
    type: "mcq",
    kicker: "Round 2 · 1986 in India",
    q: "In 1986, India won a famous Test series in England by what margin?",
    choices: ["1–0", "2–0", "2–1", "3–0"],
    answer: 1,
    note: "Captained by Kapil Dev. India's first away Test series win in England in nearly 15 years.",
    source: "https://en.wikipedia.org/wiki/Kapil_Dev",
  },
  {
    type: "tf",
    kicker: "Round 2 · 1986 in India",
    q: "The 34th National Film Award for Best Feature Film (for films released in 1986) went to a Hindi film.",
    answer: false,
    note: "It went to Tabarana Kathe (Kannada), directed by Girish Kasaravalli.",
    source: "https://en.wikipedia.org/wiki/34th_National_Film_Awards",
  },

  // ─── Round 3: 1986 at the Movies & on TV ──────────────────────────
  {
    type: "divider",
    kicker: "Round 3 of 4",
    q: "1986 at the Movies & on TV",
    sub: "Hindi cinema, Hollywood, and a daytime-TV revolution.",
  },
  {
    type: "mcq",
    kicker: "Round 3 · Movies & TV",
    q: "Which actress played the snake-woman in Nagina (1986)?",
    choices: ["Madhuri Dixit", "Rekha", "Sridevi", "Hema Malini"],
    answer: 2,
    note: "Released November 28, 1986. The second highest-grossing Indian film of the year, after Karma.",
    source: "https://en.wikipedia.org/wiki/Nagina_(1986_film)",
  },
  {
    type: "mcq",
    kicker: "Round 3 · Movies & TV",
    q: "Karma (1986), the year's top Hindi grosser, was directed by:",
    choices: ["Manmohan Desai", "Subhash Ghai", "Raj Kapoor", "Yash Chopra"],
    answer: 1,
    note: "Released August 8, 1986. Starred Dilip Kumar, Nutan, Anil Kapoor, Naseeruddin Shah, Jackie Shroff.",
    source: "https://en.wikipedia.org/wiki/Karma_(1986_film)",
  },
  {
    type: "tf",
    kicker: "Round 3 · Movies & TV",
    q: "Mr. India released in 1986.",
    answer: false,
    note: "Mr. India released May 25, 1987 — Shekhar Kapur, Anil Kapoor, Sridevi. 'Mogambo khush hua' came a year after Reeti's first birthday.",
    source: "https://en.wikipedia.org/wiki/Mr._India_(1987_film)",
  },
  {
    type: "tf",
    kicker: "Round 3 · Movies & TV",
    q: "Qayamat Se Qayamat Tak — Aamir Khan's debut — released in 1986.",
    answer: false,
    note: "QSQT released April 29, 1988. Not a 1986 film.",
    source: "https://en.wikipedia.org/wiki/Qayamat_Se_Qayamat_Tak",
  },
  {
    type: "mcq",
    kicker: "Round 3 · Movies & TV",
    q: "Which 1986 Hindi film was a remake of '12 Angry Men'?",
    choices: ["Aakhree Raasta", "Karma", "Ek Ruka Hua Faisla", "Naam"],
    answer: 2,
    note: "Directed by Basu Chatterjee. A jury-room drama, frame-for-frame remake of the 1957 Sidney Lumet classic.",
    source: "https://en.wikipedia.org/wiki/Ek_Ruka_Hua_Faisla",
  },
  {
    type: "mcq",
    kicker: "Round 3 · Movies & TV",
    q: "The highest-grossing US film of 1986 was:",
    choices: ["Crocodile Dundee", "Top Gun", "Aliens", "Platoon"],
    answer: 1,
    note: "$176.8M domestic, $353.8M worldwide. Released May 16, 1986.",
    source: "https://en.wikipedia.org/wiki/Top_Gun",
  },
  {
    type: "mcq",
    kicker: "Round 3 · Movies & TV",
    q: "James Cameron's 1986 sci-fi sequel was:",
    choices: ["The Fly", "The Terminator", "Aliens", "Predator"],
    answer: 2,
    note: "Released July 18, 1986. Sequel to Ridley Scott's 1979 Alien. Sigourney Weaver in the lead.",
    source: "https://en.wikipedia.org/wiki/Aliens_(film)",
  },
  {
    type: "mcq",
    kicker: "Round 3 · Movies & TV",
    q: "Which 1986 film won the Best Picture Academy Award?",
    choices: ["Hannah and Her Sisters", "Children of a Lesser God", "The Mission", "Platoon"],
    answer: 3,
    note: "Oliver Stone's Vietnam War drama. Released December 19, 1986.",
    source: "https://en.wikipedia.org/wiki/Platoon_(film)",
  },
  {
    type: "tf",
    kicker: "Round 3 · Movies & TV",
    q: "The Oprah Winfrey Show launched in national US syndication in September 1986.",
    answer: true,
    note: "September 8, 1986. Premiere topic: 'How to Marry the Man or Woman of Your Choice.' Ran 25 seasons.",
    source: "https://en.wikipedia.org/wiki/The_Oprah_Winfrey_Show",
  },
  {
    type: "mcq",
    kicker: "Round 3 · Movies & TV",
    q: "Crocodile Dundee — 1986's surprise comedy hit — came from which country?",
    choices: ["USA", "UK", "Australia", "New Zealand"],
    answer: 2,
    note: "Released April 30, 1986 in Australia; September 26, 1986 in the US. Starred Paul Hogan.",
    source: "https://en.wikipedia.org/wiki/Crocodile_Dundee",
  },

  // ─── Round 4: 1986 in Pop Culture, Sports & Science ───────────────
  {
    type: "divider",
    kicker: "Round 4 of 4",
    q: "1986 in Pop Culture, Sports & Science",
    sub: "Football, boxing, IPOs, and the births of some famous 40-year-olds.",
  },
  {
    type: "mcq",
    kicker: "Round 4 · Pop Culture, Sports & Science",
    q: "Which country won the 1986 FIFA World Cup?",
    choices: ["Brazil", "West Germany", "Argentina", "Italy"],
    answer: 2,
    note: "Final: June 29, 1986, Estadio Azteca. Argentina 3–2 West Germany.",
    source: "https://en.wikipedia.org/wiki/1986_FIFA_World_Cup_final",
  },
  {
    type: "mcq",
    kicker: "Round 4 · Pop Culture, Sports & Science",
    q: "Maradona's 'Hand of God' goal in the 1986 World Cup was scored against:",
    choices: ["Brazil", "England", "Belgium", "Germany"],
    answer: 1,
    note: "Quarterfinal, June 22, 1986. Followed four minutes later by the 'Goal of the Century.'",
    source: "https://en.wikipedia.org/wiki/Argentina_v_England_(1986_FIFA_World_Cup)",
  },
  {
    type: "mcq",
    kicker: "Round 4 · Pop Culture, Sports & Science",
    q: "In November 1986, Mike Tyson became the youngest heavyweight boxing champion at what age?",
    choices: ["18", "19", "20", "21"],
    answer: 2,
    note: "20 years, 4 months, 23 days. November 22, 1986 — 2nd-round TKO of Trevor Berbick.",
    source: "https://en.wikipedia.org/wiki/Trevor_Berbick_vs._Mike_Tyson",
  },
  {
    type: "mcq",
    kicker: "Round 4 · Pop Culture, Sports & Science",
    q: "Microsoft went public in March 1986 at what IPO price per share?",
    choices: ["$7", "$14", "$21", "$42"],
    answer: 2,
    note: "$21/share, first trade $25.50, closed day at $35.50. Bill Gates kept ~45% — worth ~$350M at age 30.",
    source: "https://news.microsoft.com/announcement/microsoft-goes-public/",
  },
  {
    type: "tf",
    kicker: "Round 4 · Pop Culture, Sports & Science",
    q: "Pixar was founded in 1986 when Steve Jobs bought it out of Lucasfilm.",
    answer: true,
    note: "February 3, 1986. Jobs paid $5M to George Lucas, plus $5M in working capital.",
    source: "https://en.wikipedia.org/wiki/Pixar",
  },
  {
    type: "tf",
    kicker: "Round 4 · Pop Culture, Sports & Science",
    q: "Lady Gaga, Drake, and Robert Pattinson were all born in 1986.",
    answer: true,
    note: "Gaga: March 28 · Pattinson: May 13 · Drake: October 24. (Also 1986: Emilia Clarke, Lindsay Lohan, the Olsen twins.)",
    source: "https://en.wikipedia.org/wiki/1986",
  },
  {
    type: "tf",
    kicker: "Round 4 · Pop Culture, Sports & Science",
    q: "Rafael Nadal was born in 1986.",
    answer: true,
    note: "June 3, 1986 — five days before Reeti.",
    source: "https://en.wikipedia.org/wiki/Rafael_Nadal",
  },
  {
    type: "mcq",
    kicker: "Round 4 · Pop Culture, Sports & Science",
    q: "The Billboard year-end #1 song of 1986 was:",
    choices: [
      "Take My Breath Away",
      "That's What Friends Are For",
      "Rock Me Amadeus",
      "Walk Like an Egyptian",
    ],
    answer: 1,
    note: "Dionne & Friends (Warwick, Elton John, Gladys Knight, Stevie Wonder). An AIDS-research benefit single.",
    source: "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1986",
  },
  {
    type: "mcq",
    kicker: "Round 4 · Pop Culture, Sports & Science",
    q: "The 'Brain' virus — widely considered the first PC computer virus (Jan 1986) — originated in:",
    choices: ["India", "Pakistan", "Russia", "USA"],
    answer: 1,
    note: "Created in Lahore by brothers Basit and Amjad Farooq Alvi.",
    source: "https://en.wikipedia.org/wiki/Brain_(computer_virus)",
  },
  {
    type: "tf",
    kicker: "Round 4 · Pop Culture, Sports & Science",
    q: "In December 1986, an aircraft called Voyager completed the first nonstop, unrefueled flight around the world.",
    answer: true,
    note: "Landed December 23, 1986. Pilots: Dick Rutan and Jeana Yeager. Total time: 9 days, 3 minutes, 44 seconds.",
    source: "https://en.wikipedia.org/wiki/Rutan_Voyager",
  },

  // ─── The Population Gag ───────────────────────────────────────────
  {
    type: "gag",
    kicker: "A small but important fact",
    q: "Why we hit 5 billion.",
  },

  // ─── Bonus Round: Reeti Rapid Fire (25 personal preference Qs) ────
  {
    type: "divider",
    kicker: "Bonus Round",
    q: "Reeti Rapid Fire",
    sub: "Answer quickly — no thinking! Press R to start the timer on each.",
  },
  { type: "rapid", q: "Coffee or nap?" },
  { type: "rapid", q: "Back pain or knee pain?" },
  { type: "rapid", q: "Early dinner or early bedtime?" },
  { type: "rapid", q: "Glasses on your head or glasses on your face?" },
  { type: "rapid", q: "Party all night or asleep by 10?" },
  { type: "rapid", q: "Forgot names or forgot why you walked into the room?" },
  { type: "rapid", q: "Hair fall or random grey hair?" },
  { type: "rapid", q: "Loud music or 'Can you turn that down?'" },
  { type: "rapid", q: "Netflix binge or 15-minute nap?" },
  { type: "rapid", q: "Fancy shoes or comfortable slippers?" },
  { type: "rapid", q: "Birthday cake or sugar-free cake?" },
  { type: "rapid", q: "Dance floor or sofa?" },
  { type: "rapid", q: "Young at heart or old in the knees?" },
  { type: "rapid", q: "Unlimited money or unlimited energy?" },
  { type: "rapid", q: "Alarm clock or naturally awake at 5 AM?" },
  { type: "rapid", q: "Texting or asking your kid how to use your phone?" },
  { type: "rapid", q: "Gym workout or stretching and praying?" },
  { type: "rapid", q: "Weekend party or weekend nap?" },
  { type: "rapid", q: "Reading glasses or pretending you can still read small text?" },
  { type: "rapid", q: "Memory loss or 'I know this person but forgot their name'?" },
  { type: "rapid", q: "Road trip or staycation?" },
  { type: "rapid", q: "Hot tea or heating pad?" },
  { type: "rapid", q: "Pizza or antacid after pizza?" },
  { type: "rapid", q: "Midnight celebration or 'Please let me sleep'?" },
  { type: "rapid", q: "Feeling 25 or acting 25?" },

  // ─── Bonus Round: Extra Savage ────────────────────────────────────
  {
    type: "divider",
    kicker: "Bonus Round",
    q: "Extra Savage",
    sub: "No rules. No mercy. Just questions.",
  },
  { type: "savage", q: "How many noises do you make when getting up from a chair?" },
  { type: "savage", q: "Is 40 the new 30… or just 20 with back pain?" },
  { type: "savage", q: "What hurts more: your knees or your Wi-Fi when kids are home?" },
  {
    type: "savage",
    q: "What's your wildest birthday wish — peace, sleep, or lower-back support?",
  },
  { type: "savage", q: "Are you older… or just more 'limited edition'?" },

  // ─── Finale ───────────────────────────────────────────────────────
  {
    type: "finale",
    kicker: "From all of us",
    q: "Happy 40th, Reeti.",
    sub: "Limited Edition since 1986.",
  },
];
