source 'https://rubygems.org'
gem 'jekyll', '~> 4.3'
gem 'jekyll-feed'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'jekyll-sitemap'
gem 'jekyll-seo-tag'
gem 'jekyll-toc'
gem 'kramdown-math-katex'
gem 'faraday-retry'
