#+TITLE: Donkey Kicks an Elephant!!
#+DESCRIPTION: Can a donkey kick an elephant and that too hard enough for elephant to counter? If I say yes, then you will say I have gone mad. But wait, a donkey certainly can!! So you ask how? Read today’s TOI. Yes, you are right election results...
#+DATE: 2006-11-09 22:16:00 -0600
#+CATEGORIES: Politics & Governance
#+TAGS: politics, india, united-states
#+PERMALINK: /2006/11/10/donkey-kicks-an-elephant/

Can a donkey kick an elephant and that too hard enough for elephant to counter? If I say yes, then you will say I have gone mad. But wait, a donkey certainly can!! So you ask how? Read today's TOI. Yes, you are right election results for [[http://en.wikipedia.org/wiki/United_States][the US]] [[http://www.house.gov/][Congress]] have been declared and [[http://www.democrats.org/][Democrats]] have come out with flying colors. This win has put the Democrats in-charge of the House after 1994. Also, this has put forward a threat to [[http://www.gop.com/][Republicans]] especially our Dubyaman, [[http://en.wikipedia.org/wiki/George_W._Bush][President Bush]].

If I look from [[http://maps.google.com/maps?ll=28.6133333333,77.2083333333&spn=10.0,10.0&q=28.6133333333,77.2083333333%20%28India%29&t=h][India]]'s perspective then I see a big question mark on India's gains that included free trade and outsourcing issues as Democrats are little more, in the words of Times Of India, protectionist. However, as far as nuclear deals are concerned, there is no threat as Democrats backed this deal. Also, there should be no fear as policy towards India is backed by Democrats. But the only threat is snatching away of major concessions from India.

The major thing that will get affected is Washington's policy on [[http://en.wikipedia.org/wiki/Iraq][Iraq]]. With majority and the governance of States, Bush will have to re-think on his policies that are presently being implemented on Iraq.

Apart from this, this victory of Democrats puts [[http://en.wikipedia.org/wiki/Nancy_Pelosi][Nancy Pelosi]], California lawmaker, in the House Leadership, making her the first woman in American History to be the speaker. This post is considered to be next only to [[http://en.wikipedia.org/wiki/Vice_President_of_the_United_States][Vice-President]].

If the same trend continues in Presidential elections then, we will certainly see [[http://en.wikipedia.org/wiki/Hillary_Rodham_Clinton][Hilary Clinton]] or [[http://en.wikipedia.org/wiki/Barack_Obama][Barack Obama]] as next President. I would like to see this happen and wait for their stand and policies towards India.
