#+TITLE: Do We Believe This?
#+DESCRIPTION: The East low before the blast In patient deep disdain; She let the legions thunder past, And plunged in thought again. This is a part of a poem written by Matthew Arnold(24 December 1822 – 15 April 1888), viz. Obermann Once More. This...
#+DATE: 2007-10-01 15:59:00 -0500
#+CATEGORIES: Politics & Governance
#+TAGS: politics, india
#+PERMALINK: /2007/10/01/do-we-believe-this/

The East low before the blast\\
In patient deep disdain;\\
She let the legions thunder past,\\
And plunged in thought again.

This is a part of a poem written by Matthew Arnold(24 December 1822 -- 15 April 1888), viz. Obermann Once More.

This poem is often used with reference to East by European historians specially when talking about India. The poem's meaning can be understand by the following lines from the book Struggle for Asia by Francis Low:-

“Just over a hundred years ago the people of Asia had either resolutely sealed themselves off from from all contact with the West or were incapable of defending themselves against Western governments which backed the demands of adventurous European and American traders. The great continent slumbered, immersed either in its own culture and civilization or in its own internal quarrels.”

Now tell me DO YOU BELIEVE THIS?
