#+TITLE: Literacy in India
#+DESCRIPTION: For the success of any country it is necessary that its people are educated and literate. India has been a feudal for centuries. The concept of nationhood is still new and people find it hard to understand this and therefore we see acts...
#+DATE: 2009-05-31 17:27:19 -0500
#+CATEGORIES: Politics & Governance, Society & Economy
#+TAGS: politics, society, economy, sports, india
#+PERMALINK: /2009/05/31/literacy-in-india/

For the success of any country it is necessary that its people are educated and literate. India has been a [[http://en.wikipedia.org/wiki/Feudalism][feudal]] for centuries. The concept of [[http://en.wikipedia.org/wiki/Nation][nationhood]] is still new and people find it hard to understand this and therefore we see acts of riots, religious and regional conflicts taking place everywhere in the country. Education focussing on national integration, cross-cultural sensitivity and equality has the potential to be an instrument to bring harmony and achieving social objectives besides creating a learned society.

#+begin_html
  <!--more-->
#+end_html

Lets discuss about the [[http://en.wikipedia.org/wiki/National_literacy_mission][National Literacy Mission]] ([[http://www.nlm.nic.in/][NLM]]), set up in May 1987 that aimed to attain 75% literacy by 2007 and had run several schemes to ensure that this target is achieved. But we were able to attain only 65% literacy (as per[[http://censusindia.gov.in/][Census of India]] 2001) or 61% literacy (as per [[http://www.plan.org.au/ourwork/asia/india][Plan Australia]]).  The current literacy rate is hard to be calculated but taking into account the growth of a decade, we can say that though not confidently that we have not hot hit the target of 75% literacy.  But achieving 65% literacy rate was still an overwhelming task given to understand the size of our nation. However, we cannot make this excuse as when we had set the target in 1988 we must have thought everything before setting the target. In short, we have failed again.

Nearly 70 percent of the country's illiterate population belong to the eight states of [[http://en.wikipedia.org/wiki/Uttar_Pradesh][Uttar Pradesh]], [[http://en.wikipedia.org/wiki/Bihar][Bihar]], [[http://en.wikipedia.org/wiki/Andhra_Pradesh][Andhra Pradesh]], [[http://en.wikipedia.org/wiki/West_Bengal][West Bengal]], [[http://en.wikipedia.org/wiki/Maharashtra][Maharashtra]], [[http://en.wikipedia.org/wiki/Rajasthan][Rajasthan]], [[http://en.wikipedia.org/wiki/Madhya_Pradesh][Madhya Pradesh]] and [[http://en.wikipedia.org/wiki/Karnataka][Karnataka]]. These states have not shown any major improvement in the government's flagship programmes, the [[http://www.education.nic.in/ssa/ssa_1.asp][Sarva Shiksha Abhiyan]] (Education for All), for universalisation of elementary education in a time bound manner, and the National Literacy Mission.

The failure of states to implement the NLM has forced the government to set another target - to attain 80 percent literacy rate by the end of 2012, and complete literacy three years later - by 2015. The government has earmarked a whopping Rs.850 billion ($21 billion) - five times the budget allocated earlier - for the education sector in the [[http://planningcommission.nic.in/plans/planrel/fiveyr/welcome.html][11th Five Year Plan]], which ends in 2012.

[[http://portal.unesco.org/en/ev.php-URL_ID=29008&URL_DO=DO_TOPIC&URL_SECTION=201.html][UNESCO]], which assists the mission, had in a report criticised the way the NLM was progressing, stating that

#+begin_quote
India was nowhere in terms of eradicating illiteracy.
#+end_quote

Renowned educationist [[http://en.wikipedia.org/wiki/Yash_Pal][Professor Yashpal]] has questioned the credibility of the UNECO report, saying that

#+begin_quote
Who are they (UNESCO) to tell us? They aren't aware of the ground situation and realities of our country.
#+end_quote

He hopes that the Mission would complete its new target of complete literacy by 2015.

#+begin_quote
The government is committed to eradicating illiteracy. It is its top agenda. All the agencies are being put to work to ensure that the literacy target is met on time.
#+end_quote

But the truth remains that we have failed in achieving our set targets and that is due to few states who failed to implement NLM. The lack of zeal and strong-will of the administration and political setup has been the main reason for this failure.

Then what should be done. The [[http://goidirectory.nic.in/][GOI]] should set yearly targets for every state and this should be evaluated at the end of the year. If the state fails to achieve the target, necessary actions should be taken against the government of these states so as to ensure accountability of the governments of these states.

It is important that these states realize the urgency of NLM. This will mean the education of political leaders so as to make them aware of this urgency. Also, the people who are educated should come forward and help in achieving this target. This means, that not only GOI, but also, the people of India need to work on this. There are many NGOs that are working on NLM and are getting grants for their work. But they lack support of masses. In India, we have Reservation in education for socially backward people and many people from these groups have achieved a good education and attained a good status in society. These people should come forward to help government in attaining the targets of NLM.

Until and unless the government gets support of states, bureaucracy, and its people, the targets will remain the distant dream. So, we should realize this and come forward and help government in achieving the 100% literacy by 2015. It is difficult but not impossible.
