#+TITLE: UNITED NATIONS SECURITY COUNCIL REFORMS
#+DESCRIPTION: Oct 24th was marked as UN Day. US President paid a State visit to India and gave us a hope of permanent membership in UNSC and now US has cautioned against expecting any breakthrough “anytime soon” on the UN Security Council reforms,...
#+DATE: 2010-11-16 15:04:47 -0600
#+CATEGORIES: Politics & Governance
#+TAGS: politics, india, united-nations
#+PERMALINK: /2010/11/16/united-nations-security-council-reforms/

Oct 24th was marked as [[http://www.un.org/en/events/unday/2009/][UN Day]]. [[http://en.wikipedia.org/wiki/Barack_Obama's_visit_to_India][US President paid a State visit to India]] and gave us a hope of [[http://en.wikipedia.org/wiki/United_Nations_Security_Council#Permanent_members][permanent membership]] in [[http://en.wikipedia.org/wiki/United_Nations_Security_Council][UNSC]] and now US has cautioned against expecting any breakthrough “anytime soon” on the UN Security Council reforms, dampening [[http://maps.google.com/maps?ll=28.6133333333,77.2083333333&spn=10.0,10.0&q=28.6133333333,77.2083333333%20(India)&t=h][India]]'s hopes for a permanent seat. All is game and it will continue. I do not have any issues with whatever is happening. I have no interest in it either. We get a permanent seat or not, it does not make difference. We can make difference without being a part of UNSC. I am only interested in reforms in [[http://www.un.org/sc/][United Nations Security Council]] and till that happen, I do not see any difference any country would make by becoming a permanent member of UNSC.

I have a question that I want to ask the Governments of two largest [[http://en.wikipedia.org/wiki/Democracy][democracies]] of the world. Do not they see the un-democratic structure of UNSC when they keep on talking about advantages of democratic setup and boast of being democracies themselves? Both the countries talk about creating more and more democracies and moving away from imperialism of any kind. However, why cannot we have a democratic structure in UNSC when the world is growing more democratic then before?

The provision of permanent membership is shameful and against the concept of democracy. It is against progressiveness and is [[http://en.wikipedia.org/wiki/Imperialism][imperialistic]] in nature as a single permanent member can abandon a collective decision taken by majority of 192 nations. I had long back suggested some [[http://palakmathur.wordpress.com/2008/10/29/united-nations-security-council-reforms-2/][reforms]]. However, I think though they are less imperialistic they are not democratic. We need to think about bringing democracy in UNSC.

I hope that India will move away from being a member of UNSC and rather will look towards making UNSC a democratic setup where people around the world are free to decide their future rather then leaving their destinies in the hands of few permanent members.
