#+TITLE: Changed the Template
#+DESCRIPTION: Finally today I changed the template for three of  my blogs on blogger, viz. Renaissance, Aatmiyata and Tech Foci . Was getting bore while doing deployment. Actually, I have been deployments for past few weeks and now I am not...
#+DATE: 2010-03-05 18:18:05 -0600
#+CATEGORIES: Personal Essays
#+TAGS: personal, opinion
#+PERMALINK: /2010/03/06/changed-the-template/

Finally today I changed the template for three of  my blogs on blogger, viz. [[http://palakmathur.blogspot.com][Renaissance]], [[http://aatmiyata.blogspot.com][Aatmiyata]] and [[http://techfoci.blogspot.com][Tech Foci]] . Was getting bore while doing deployment. Actually, I have been deployments for past few weeks and now I am not interested in doing so. So, was just thinking about the days back in Infosys. You will have to believe that whenever I think about Infosys, first thing that clicks my mind is about InfyBlogs - how I used to change the templates of the blog. More than writing, for few months I was interested in only making new templates for my blog. It used to satisfy my creative thirst.

#+begin_html
  <!--more-->
#+end_html

Today was the similar day. I was thinking the same and suddenly I thought to change the blog template. Actually, I was going through the setting when I saw that I can add upto 10 pages to my blog. I thought this is a good thing actually. So, added a page. My old template was so simple that it was not giving a feel for tabs on the top of the page. Therefore searched the net and found this template.

I think after May, I will indulge in this creativity wherein I will create templates for blogger now. Hope I succeed!
