#+TITLE: [Book Review] The Alchemist: A Fable About Following Your Dream by Paulo Coelho
#+DESCRIPTION: ** I don’t like self-help books. But on strong recommendation from my wife and others, I gave a chance to myself and read the book. I liked the story and kept reading until I finished it. Few of my friends did not like the book but I...
#+DATE: 2011-04-24 18:42:54 -0500
#+CATEGORIES: Books & Reading
#+TAGS: book-review
#+PERMALINK: /2011/04/24/book-review-the-alchemist-a-fable-about-following-your-dream-by-paulo-coelho/
#+FEATURED_IMAGE_ALT: Book cover: The Alchemist by Paulo Coelho

​**

I don't like [[http://en.wikipedia.org/wiki/Self-help_book][self-help books]]. But on strong recommendation from my wife and others, I gave a chance to myself and read the book. I liked the story and kept reading until I finished it. Few of my friends did not like the book but I would recommend them to read it just like a story and it would be a good read.  I have nothing to say about the story as most of us know about it or it is easily available on internet.The novel tells the story of a of Andalusian shepherd boy named Santiago who has a dream and has the courage to follow it.  He listens to  “the signs” and ventures on a journey of exploration and discovery in search of a hidden treasure somewhere near the pyramids in [[http://www.lonelyplanet.com/egypt][Egypt]]. Along the way he meets a Gypsy woman, a man who calls himself king, and an alchemist, all of whom points Santiago in the direction of his quest. And finally does a self-discovery and is enlightened.  It is a reawakening for him.  A renaissance.

When he decides to go, his father's only advice is

#+begin_quote
Travel the world until you see that our castle is the greatest, and our women the most beautiful.
#+end_quote

In his journey, Santiago sees the greatness of the world, and meets all kinds of exciting people like kings and alchemists. However, by the end of the novel, he discovers that “treasure lies where your heart belongs”, and [[http://bookreviews.nabou.com/reviews/thealchemist.html][that the treasure was the journey itself, the discoveries he made, and the wisdom he acquired]].The language was simply beautiful and expressions were impressive. The whole book was moving like a movie in mind. I have listened lot of good things about Paulo and his books and with that, I had made the impression that I won't be able to read any of his books. But this book proved me wrong. I could read it.  Most importantly, I came to know that a the famous dialogue from [[http://www.imdb.com/title/tt1024943/][Om Shanti Om]] is taken from this book ;-): > When you really want something to happen, the whole universe conspires so that your wish comes true

The story is not new and we have read it many a times in many other sources. It was one of the stories from [[http://en.wikipedia.org/wiki/Panchatantra][Panchtantra]] or [[http://www.lonelyplanet.com/morocco/the-mediterranean-coast-and-the-rif/tangier/sights/architectural-cultural/1001-nights][Arabian Nights]].  But if you have forgotten them, then go and read it.

****** Related Articles
:PROPERTIES:
:CUSTOM_ID: related-articles
:END:
- [[http://yilmazalimoglu.com/2011/04/08/paulo-coelho-the-alchemist-and-deserts-and-mountains/][Paulo Coelho, “The Alchemist” and “Deserts and Mountains”]] (yilmazalimoglu.com)
- [[http://alittlebitofthisandalittlebitofthat.wordpress.com/2011/02/06/the-alchemist/][The Alchemist]] (alittlebitofthisandalittlebitofthat.wordpress.com)
- [[http://bridgetsbooks.wordpress.com/2011/02/02/the-alchemist-paul-coelho/][The Alchemist - Paul Coelho]] (bridgetsbooks.wordpress.com)
- [[http://caughtbetweenthepages.wordpress.com/2011/03/11/the-alchemist-by-paulo-coelho/][The Alchemist by Paulo Coelho]] (caughtbetweenthepages.wordpress.com)
- [[http://eastbird.wordpress.com/2011/04/06/review-the-alchemist/][Review: The Alchemist]] (eastbird.wordpress.com)
- [[http://witneybookfestival.wordpress.com/2011/02/27/the-10-most-read-books-in-the-world-today/][The 10 most read books in the World today]] (witneybookfestival.wordpress.com)
- [[http://sandra2891svizzera.wordpress.com/2011/01/24/a-born-writer/][Me : A Born Writer...]] (sandra2891svizzera.wordpress.com)
