#+TITLE: Happiness
#+DESCRIPTION: I was going through Bruno’s One Minute Email that I subscribed while I was working for VCustomer. It was after a long time that I checked my email account on india.com, where we all registered as it was the only email account accessible...
#+DATE: 2011-02-02 16:30:34 -0600
#+CATEGORIES: Personal Essays
#+TAGS: personal, opinion, india
#+PERMALINK: /2011/02/02/happiness/

I was going through Bruno's One Minute Email that I subscribed while I was working for VCustomer. It was after a long time that I checked my email account on [[http://www.india.com][india.com]], where we all registered as it was the only email account accessible there. Oh, sorry, I forgot my way.

One of the recent emails has this old Chinese Proverb:-

#+begin_quote
If you want hapiness for an hour, take a nap;\\
If you want hapiness for a day, go fishing;\\
If you want hapiness for a year, inherit a fortune;\\
If you want hapiness for a lifetime, help somebody!
#+end_quote

“Helping” is a word that needs interpretation. Giving money to a good cause is one way but it's not the only one. Sometimes helping simply means taking the time to listen to someone sharing a hurt, giving someone a helping hand, making an unexpected phone call to wish someone good luck, showing compassion to someone in trouble.

#+begin_quote
I discovered a long time ago that if I helped people get what they wanted,\\
I would always get what I wanted and I would never have to worry.\\
- Anthony Robbins
#+end_quote

There is more to hapiness. Just waiting for it and thinking when such and such thing happen I will be happy is foolish. Yes, I am a fool. I am still waiting for something to happen that will make me happy.

Are you a fool too??? Don't be!!!!

​##Cross-posted from my blogpost here:- http://www.ilaaka.com/happiness
