#+TITLE: Why G-20 is a failure or will be one?
#+DESCRIPTION: Prof. Nouriel Roubini, the famed economist who is credited with predicting the global financial crisis comments on the utter failure of the G-20 in giving global leadership.  Recently he cited reasons for this failure. I am just putting...
#+DATE: 2011-02-24 03:31:23 -0600
#+CATEGORIES: Society & Economy, Politics & Governance
#+TAGS: society, economy, politics, india
#+PERMALINK: /2011/02/24/why-g-20-is-a-failure-or-will-be-one/

Prof. [[http://en.wikipedia.org/wiki/Nouriel_Roubini][Nouriel Roubini]], the famed economist who is credited with predicting the [[http://en.wikipedia.org/wiki/Financial_crisis_of_2007%E2%80%932010][global financial crisis]] comments on the utter failure of the G-20 in giving global leadership.  Recently he cited reasons for this failure. I am just putting them down here and awaiting comments, if any. [[http://www.bworldonline.com/content.php?title=Our%20G-Zero%20world&id=26445][This is available on internet elsewhere as well]].

#+begin_html
  <!--more-->
#+end_html

- First, when discussion moves beyond generic principles into detailed policy proposals, it's much more difficult to reach clear agreements among 20 negotiators than among seven.

- Second, G-7 leaders share a belief in the power of free markets to generate long-term prosperity and in the importance of democracy for political stability and social justice. The [[http://en.wikipedia.org/wiki/G-20_major_economies][G-20]], on the other hand, includes autocratic governments with different views about the role of the state in the economy, and on the [[http://en.wikipedia.org/wiki/Rule_of_law][rule of law]], property rights, transparency, and freedom of speech.

- Third, the Western powers now lack the domestic political consensus and financial resources to advance an international agenda. The US is politically polarized, and must at some point begin to reduce its budget deficit. [[http://en.wikipedia.org/wiki/Europe][Europe]] is preoccupied with its attempt to save the eurozone, and has no common foreign or defense policy. And Japan's political stalemate on structural reforms has left it helpless to stem long-term economic decline.

- Finally, rising powers like China, India, and Brazil are far too focused on managing the next stage of their domestic development to bear the financial and political costs that come with new international responsibilities.

- Why should we care?  In short, for the first time since the end of [[http://en.wikipedia.org/wiki/World_War_II][World War II]], no country or strong alliance of countries has the political will and economic leverage to secure its goals on the global stage. This vacuum may encourage, as in previous historical periods, the ambitious and the aggressive to seek their own advantage.

- In such a world, the absence of a high-level agreement on creating a new collective-security system -- focused on economics rather than military power -- is not merely irresponsible, but dangerous. A G-Zero world without leadership and multilateral cooperation is an unstable equilibrium for global economic prosperity and security.
