#+TITLE: Have some respect for the Constitution
#+DESCRIPTION: Mr Kejriwal says, “Anna Hazare is above Parliament and that he has the right to do so as a citizen … Every citizen is above Parliament.” If this is the understanding of a person who was once part of Indian Revenue Services then no doubt...
#+DATE: 2011-10-11 21:36:50 -0500
#+CATEGORIES: Society & Economy, Politics & Governance, Personal Essays
#+TAGS: society, economy, politics, personal, opinion, india
#+PERMALINK: /2011/10/11/have-some-respect-for-the-constitution/

Mr Kejriwal says, “[[http://en.wikipedia.org/wiki/Anna_Hazare][Anna Hazare]] is above [[http://en.wikipedia.org/wiki/Parliament][Parliament]] and that he has the right to do so as a citizen ... Every citizen is above Parliament.” If this is the understanding of a person who was once part of Indian Revenue Services then no doubt he was not even suited for any of the services. He must first need to clear his concepts on Polity and then give arguments. His arguments are unnecessarily provocative. It is not that individual citizens are above Parliament. The Parliament represents the collective will of the people elected through a [[http://en.wikipedia.org/wiki/Democracy][democratic process]]. He must remember the dictum, “However high one may be, the law is above.” Parliament is the reflection and the representation of the voice of the majority. Parliament is the collective voice ofIndiaand has the authority to run the country.

Though Mr. Hazare started out with his movement to fight corruption, he seems to be very selective now in choosing his targets. If the Jan Lokpal Bill is not passed by Parliament in Winter Session that will start in November, then Team Anna has every right to create public opinion in favour of the Bill and fight the government in elections. Some personalities accused of corruption are behind bars and the system is working slowly. The kind of frequent threats being held out by Mr. Hazare and [[http://en.wikipedia.org/wiki/Civil_society][civil society]] will cause damage to parliamentary democracy and result only in chaos.

There are few questions that I want to ask Mr. Kejriwal and Team Anna. Can a democracy allow a group of individuals to define ‘change,' however well intended it may be, without the legitimate authority of the people? Have they lost faith in democracy and think that only one individual can set matters right in the country?

If they have lost faith in [[http://en.wikipedia.org/wiki/Parliamentary_system][Parliamentary democracy]] and the Constitution, then why do they want Parliament to pass a law? Go ahead and violently turn the Constitution down and act as per their whims.

It is a fact that Team Anna has mobilised people to fight against corruption. No doubt, the [[http://en.wikipedia.org/wiki/United_Progressive_Alliance][UPA]] has fuelled corruption, but it cannot be taken to be the sole agent of corruption. Every Indian needs a corruption-free nation. However, [[http://en.wikipedia.org/wiki/Political_corruption][graft]] is omnipresent. It is not individual specific or party specific. Team Anna should not be biased for or against any party. The Gandhian movement was against the British as they had colonised India. But a similar struggle cannot be equal to a movement against one party. Can it be? The movement must have a cause to uproot a social evil and not the party in power when it is in majority. At least have some respect for the Constitution!! It is not that Constitution has failed us, it is we who have failed the Constitution.

****** Related articles
:PROPERTIES:
:CUSTOM_ID: related-articles
:END:
- [[http://ktrmurali.wordpress.com/2011/10/11/why-can%e2%80%99t-team-anna-wait-until-the-winter-session/][Why can't Team Anna wait until the Winter Session?]] (ktrmurali.wordpress.com)
- [[http://amalwin.wordpress.com/2011/08/26/ends-dont-justify-the-means/][Ends don't justify the Means!]] (amalwin.wordpress.com)
- [[http://news.google.com/news/url?sa=t&fd=R&usg=AFQjCNG9JUyQjsmd745LyNEuAed_7TmD6g&url=http://www.thehindu.com/news/national/article2370253.ece][Parties back Anna's right to dissent, but reject his main demand - The Hindu]] (news.google.com)
- [[http://indialawyers.wordpress.com/2011/09/06/%e2%80%98government-has-not-conceded-anything/][‘Government has not conceded anything’]] (indialawyers.wordpress.com)
