#+TITLE: Pune Mathur Association's Summer Dhamaka
#+DESCRIPTION: Ref: Taken from Priti Mathur’s blog Mathur Association, Pune organized grand Summer Dhamaka for all the Mathurs residing in Pune on April 16th at Ivy Studio, Viman Nagar. All the members with their families were invited to attend the...
#+DATE: 2011-04-21 15:47:11 -0500
#+CATEGORIES: Politics & Governance
#+TAGS: politics, pune
#+PERMALINK: /2011/04/21/pune-mathur-associations-summer-dhamaka/

* Ref: Taken from Priti Mathur's [[http://wp.me/p1wBJI-r][blog]]
:PROPERTIES:
:CUSTOM_ID: ref-taken-from-priti-mathurs-blog
:END:
Mathur Association, Pune organized grand Summer Dhamaka for all the Mathurs residing in Pune on April 16th at Ivy Studio, Viman Nagar. All the members with their families were invited to attend the function and were engrossed by captivating cultural activities, games and dinner.

The program started very aptly with “Meet and Greet each other” and then the crispy evening went ahead with excellent performance of Ghazal and Geet. It was extremely good to watch a dance performance by a young upcoming artist on a medley of songs. The highlight of the function was the glamorous “Fashion Show”, a ramp full of lights, music and smart participants- from kids to senior citizens. The fun-filled evening was full of games and of course Tambola. The Dhamaka concluded with a prize distribution ceremony and splendid dinner with yummy desserts.

The association wants to pay gratitude to all the members who made the evening so wonderful by gracing the occasion and making the event a grand success. This is one of the biggest and most interactive Mathur Association's functions in the city recently. The aim of the association is to involve more and more young and energetic youths in the committee for greater achievements in the future.
