#+TITLE: Why use GDP (nominal) instead of GDP (PPP) when comparing two nations?
#+DESCRIPTION: For example: In India majority of people are poor, and receive subsidized grains (like 1 kilo rice for 3 Rs, kerosene etc. from PDS shops. In America poor people are supported by Government by food stamps and social security cheques....
#+DATE: 2011-02-19 09:52:28 -0600
#+CATEGORIES: Society & Economy
#+TAGS: society, economy, india
#+PERMALINK: /2011/02/19/why-use-gdp-nominal-instead-of-gdp-ppp-when-comparing-two-nations/

For example:

In India majority of people are poor, and receive [[http://en.wikipedia.org/wiki/Subsidy][subsidized]] grains (like 1 kilo rice for 3 Rs, kerosene etc. from [[http://en.wikipedia.org/wiki/Public_Distribution_System][PDS]] shops.

In America [[http://en.wikipedia.org/wiki/Poverty][poor people]] are supported by Government by food stamps and social security cheques.

Now comparing two nations, [[http://en.wikipedia.org/wiki/Gross_domestic_product][GDP]] ([[http://en.wikipedia.org/wiki/Purchasing_power_parity][PPP]]) wise,

Obviously majority of Indians are poor, and majority of them get cheap- subsidized stuff, the purchasing power parity of India may look better than Americans.

But does it really mean India is financially more powerful than America just because Indians can buy more stuff in local market compared to Americans?

No, because financial activity is not limited to local market.

We've to import crude oil from Middle east and buy jet-planes, missiles from Russia,France and Israel.

We've buy pulses and onions from Africa and Pakistan(!),*Those people are not going to sell us stuff with subsidy in Rupees, like we get in our local market.*

*They'll ask hard dollars (or gold or diamonds) as payment.* So there, in [[http://en.wikipedia.org/wiki/Globalization][international market]], America can purchase more crude oil, fighter-jets, missiles and onions compared to India, even though its GDP-PPP wise it may not be powerful as India.

Even China can buy more stuff internationally than we can, because our forex reserve is only 270 billion, while Chinese got 1400 billion $!

GDP at PPP gives us only picture of how much stuff we can buy within our country.

GDP at nominal rate ($) gives us bigger-picture of how much stuff  we can buy internationally.

Using GDP (nominal), it becomes easier to compare two nations' financial strength, by comparing their ability to purchase in international market in same currency (dollars). The one who has more $$, can purchase more stuff internationally.

So bigger the GDP (Nominal), powerful a country is financially. While in case of GDP(PPP) we cannot say with confidence that bigger the GDP (PPP) is, powerful a country  is financially, because they may be heavily-subsidizing it.
