#+TITLE: [Banking in India] Story of State Bank of India
#+DESCRIPTION: Note:I am starting with a series on Banking in India. Will try to include everything regarding Indian Banking System that is necessary from examinations point of view. To start with here is the Story of State Bank of India. I selected...
#+DATE: 2011-04-27 00:56:14 -0500
#+CATEGORIES: Society & Economy
#+TAGS: society, economy, india
#+PERMALINK: /2011/04/27/banking-in-india-story-of-state-bank-of-india/

*Note*:/I am starting with a series on [[http://en.wikipedia.org/wiki/Banking_in_India][Banking in India]]. Will try to include everything regarding Indian Banking System that is necessary from examinations point of view. To start with here is the Story of [[http://www.statebankofindia.com/][State Bank of India]]. I selected SBI because I have a special place for SBI in my life. It has a part in shaping my life. How? It is the bank where my father, two of my uncles (tauji and chacha) and above all my grandfather (babaji) served./

The oldest bank *in existence* in India is the State Bank of India, which originated in the *[[http://en.wikipedia.org/wiki/Bank_of_Calcutta][Bank of Calcutta]]* in June 1806, which almost immediately became the *Bank of Bengal*. This was one of the three presidency banks, the other two being the *[[http://en.wikipedia.org/wiki/Bank_of_Bombay][Bank of Bombay]]* and the *[[http://en.wikipedia.org/wiki/Bank_of_Madras][Bank of Madras]]*, all three of which were established under charters from the [[http://en.wikipedia.org/wiki/East_India_Company][British East India Company]]. For many years the Presidency banks acted as quasi-central banks, as did their successors. The three banks merged in*1921*to form the *[[http://en.wikipedia.org/wiki/Imperial_Bank_of_India][Imperial Bank of India]]*, which, upon India's independence, became the *State Bank of India*.

****** Related Articles
:PROPERTIES:
:CUSTOM_ID: related-articles
:END:
- [[http://wiki.answers.com/Q/What_are_the_functions_of_sbi_bank][What are the functions of sbi bank]] (wiki.answers.com)
