#+TITLE: [Book Review] Hot Tea Across India by Rishad Saam Mehta
#+DESCRIPTION: For a long time I wanted to read a travelogue – beautiful images and memories captured in one book. Therefore, when BlogAdda gave me an opportunity to review one, I grabbed it. It is another story that how I received it after two weeks....
#+DATE: 2012-01-30 00:28:16 -0600
#+CATEGORIES: Books & Reading
#+TAGS: book-review, travel, india
#+PERMALINK: /2012/01/30/book-review-hot-tea-across-india-by-rishad-saam-mehta/

For a long time I wanted to read a travelogue -- beautiful images and memories captured in one book. Therefore, when BlogAdda gave me an opportunity to review one, I grabbed it. It is another story that how I received it after two weeks. It is better late than never and so here I am, writing a review, after having read the book.

Tea is one beverage that is loved by everyone from the President of India to me sitting in the comfort of my home and writing this review. If you are out of ideas, Tea is a drink, which refreshes you and the ideas come flowing out at a faster pace. Tea is made in different styles across India. Though different in style, one thing is common across everywhere -- well-brewed tea is an unmatched refresher.

The book in question has used this marvelous drink as part of its title. One will assume that tea will be the centre of each of the story or anecdote; however, that is not the case. The author has used Tea in various forms in different stories -- in some Tea is the protagonist and in others it plays a supporting role while in few others it has been used metaphorically.

The author portrays his experience in a very lucid and simple language and displays a sense of humor that is both pragmatic and pleasurable. The book covers trips, anecdotes and stories in varied lengths. Some trips are short while others are spread over few chapters. The book is not only about trips and tea -- it is also about people. He describes various characters across the book -- Doltu, a local Himachali lad, Mouneet, a friend and a whiz in computers, and Kapil from NR Cells (Railways) are some who grab attention. Besides, the author has devoted an entire chapter for his Guides across various locations in India -- Uncle ‘Moustachioed' Mukesh at [[http://en.wikipedia.org/wiki/Jaisalmer][Jaisalmer]], the great S.N.Keshav Murthy at the [[http://maps.google.com/maps?ll=13.1628611111,75.8605555556&spn=0.01,0.01&q=13.1628611111,75.8605555556%20(Chennakesava%20Temple)&t=h][Chennakesava Temple]], and Ashutosh Tripathi at Khajurao -- are the few about whom he has talked about at good length.

The experiences shared cover all the masalas that are involved in a Bollywood flick-- drama, chill, thrill, comedy, action and adventure all are beautifully brewed together and served and presented beautifully.

When I had ordered the book, I had thought since it belongs to Travel genre, it would have some pictures; there is none. I was disappointed to an extent. However, -it is also important to realize that the book is more about style of writing and experiences and not the regular travel description.

Overall, an excellent book for a light read. The book will not take much of your time and you can read it in a go though it does not require to be completed in one sitting. It is a nice book, which can be read while traveling, or just before going to sleep, or waiting for your wife outside her office or wherever you feel like. You do not need to be in a serious reading mode while picking this up. So, grab your copy now and enjoy.

My rating 7/10.

This review is a part of the [[http://blog.blogadda.com/2011/05/04/indian-bloggers-book-reviews][Book Reviews Program]] at [[http://www.blogadda.com/][BlogAdda.com]]. Participate now to get free books!

****** Related articles
:PROPERTIES:
:CUSTOM_ID: related-articles
:END:
- [[http://palakmathur.wordpress.com/2011/12/25/book-review-transforming-capitalism-improving-the-world-for-everyone-by-arun-maira/][[Book Review] Transforming Capitalism Improving the World for Everyone by Arun Maira]] (palakmathur.wordpress.com)
- [[http://personalconcerns.wordpress.com/2012/01/17/book-review-hot-tea-across-india/][Book Review: Hot Tea Across India]] (personalconcerns.wordpress.com)
