#+TITLE: Learn Python - Resources
#+DESCRIPTION: Here I am listing few of the resources that I think will be good for someone to refer if (s)he wants to learn Python.
#+DATE: 2012-08-09
#+CATEGORIES: Technology, Software Engineering
#+TAGS: technology, software, india
#+PERMALINK: /2012/08/09/learn-python-resources/
#+COMMENTS: true

Python is a dynamic object-oriented programming language that can be used for many kinds of software development. It offers strong support for integration with other languages and tools, comes with extensive standard libraries, and can be learned in a few days. Many Python programmers report substantial productivity gains and feel the language encourages the development of higher quality, more maintainable code.

Here I am listing few of the resources that I think will be good for someone to refer if (s)he wants to learn Python. ##Python Reference:## [[http://www.python.org/doc/current/][Official Documentation]] - Official Current Documentation

​##Learn Python:## [[http://www.greenteapress.com/thinkpython/][Think Python: How to Think Like a Computer Scientist by Allen Downey]] - is both a good introduction to programming as well as a good introduction to the Python language\\
Learning Python, Fourth Edition by Mark Lutz - I think the great first book for learning Python\\
[[http://www.mindview.net/Books/TIPython][Thinking in Python]] - Nice book available online.\\
[[http://www.diveintopython.net/][Dive Into Python by Mark Pilgrim]] - book aimed at experienced professional programmers who want to hit the ground running with a new language [[http://inventwithpython.com/][Invent with Python]] - Book is available at amazon and also available free for online reading and teaches you how to build Computer games.

​##Other Resources:## [[http://www.pythonware.com/daily/][The Daily Python URL]] - Daily Python URL. Has not been updated for long time now but still has some good links to consider reading. [[http://www.coderanch.com/forums/f-112/Jython-Python][Java Ranch Python/Jython Forum]] - One of the best available online community for Programmers, JavaRanch not only caters to Java programming languages but plethora of other languages as well. Meet Python/Jython experts and cohorts on this forum. [[http://mail.python.org/mailman/listinfo][Python Mailing Lists]]- List of all Python Mailing lists worldwide< [[http://python.org.in/][Python Software Society of India]] - Python group India with its sub-chapters [[http://in.pycon.org/2012/][Pycon India 2012 Website]] - Official Website of Pycon India 2012.

Let me know if any of the links are broken. As of 9th August 2012, all the links were up and running.
