#+TITLE: Rahul Gandhi Hatao, Desh Bachao
#+DESCRIPTION: “Rahul Gandhi Hatao, Desh Bachao"
#+DATE: 2021-02-22
#+CATEGORIES: Politics & Governance, Personal Essays
#+TAGS: politics, personal, opinion, india
#+PERMALINK: /2021/02/22/indian-national-congress-destroy-india/
#+COMMENTS: true

Indian National Congress will destroy the country. That is true. Why? Because we do not have a strong opposition and we will not have a strong opposition till we have Gandhi family at the top.

Rahul Gandhi is a sidelined politician in India who does not have mass following outside of some “Chamchas” in Congress. I think Congress realizes that, but for reason unknown, do not act.

If Congress has to survive, get rid of Gandhi. I remember in 1990s Congress gave a slogan, “Soniya Lao, Desh Bachao!” Let's change it to - “Rahul Gandhi Hatao, Desh Bachao!”

If Rahul Gandhi remains at the top of Congress, there will be no formidable opposition to Modi and BJP. Without a great opposition, there cannot be a great government and thus a threat to having and protecting a great democracy.

Congress has vowed to rebuild themselves. I think it is the high time. If they are genuinely interested, then the first thing they must do is reorganize themselves. Sonia Gandhi and her family should give way to people to lead the party based on merit.

Dynasty politics has ruined Congress and it is the time to part ways. Now, should Sonia Gandhi and her family decide who gets to be the next President of Congress? No! Let the organization decide under one condition that no one from Gandhi family should be at helm.

Gandhi family can be part of the party but just as do other MPs, MLAs and workers and work hard to get what they deserve rather than what they think they should.
