#+TITLE: Graduated from Georgia Tech
#+DESCRIPTION: Finally, I completed my MS in Computer Science from Georgia Institute of Technology
#+DATE: 2022-12-12
#+CATEGORIES: Life Events
#+TAGS: personal
#+PERMALINK: /2022/12/12/graduated-gatech/
#+COMMENTS: true

​#Copied from LinkedIn I'm excited to announce that I recently completed my MS in Computer Science from Georgia Institute of Technology or Georgia Tech, with a specialization in Computing Systems.

Some of my favorite courses during the course of my studies were Gradute Introduction to Operating Systems (GIOS), Software Analysis and Test (SAT), Network Science (NS), High Performance Computing Architecture (HPCA), Knowledge Based Artificial Intelligence (KBAI), and Introduction to Graduate Algorithms (GA).

It wasn't always easy balancing work, family, and school, especially during the pandemic, but I'm proud to have made it through and achieved this important milestone. I'm looking forward to seeing where this degree takes me and am grateful for all the support I received along the way. Special thanks to my wife, Priti for sticking with me. This degree certainly tested our relationship at times. #humblebrag #newlymintedMS #computerscience #computingsystems
