#+TITLE: Mir and My H1B and GC Travails
#+DESCRIPTION: Here I try to express my life, H1B and GC travails using Mir's couplets.
#+DATE: 2022-11-26
#+CATEGORIES: Personal Essays, Poetry & Literature
#+TAGS: personal, opinion, poetry, travel, united-states, agra, pune, hindi
#+PERMALINK: /2022/11/26/H1B-and-Me-With-Mir/
#+COMMENTS: true

I have been in United States of America for a while now and even though I am a legal resident, chances of me getting an employment-based Green Card (GC) are very slim.

I share the sentiment behind the following couplets from Mir Taqi Mir:

#+begin_example
    चला अकबराबाद से जिस घड़ी
    दर-ओ-बाम पर चस्म-ए-हसरत पड़ी
#+end_example

Like Mir, who left Agra (Akbarabad in the couplet above) to find employment, I too left Agra in search of a job - first to Delhi, then Mysore, Pune and finally Dallas. It was difficult. My parents still live in Agra and leaving Agra was leaving a big part of my heart behind. Had to harden whatever was left to be able to live and like Mir said

#+begin_example
    की तर्क-ए-वतन पहले क्यूँ कर करूँ
    मगर हर कदम दिल को पत्थर करूँ
#+end_example

And this all happened for what - a job to live a life.

#+begin_example
    ज़माने नें रखा मुझे  मुत्तसिल
    परागन्द रोज़ी, परागन्द दिल
        
#+end_example

The above couplet is so right, that though I found the job, my life is still scattered and it is life that is keeping me busy.

#+begin_example
    गयी कब परेशानी–ए-रोज़गार
    रहा मैं तो हम ताले-ए-जुल्फ-ए-यार
    
    
#+end_example

And the above couplet explains my issues with H1B and GC much better than I will be ever able to explain.
