#+TITLE: Bhupinder Singh
#+DESCRIPTION: Om Shanti! Bhupinder Singh ji your voice will continue to mesmerize us.
#+DATE: 2022-07-19
#+CATEGORIES: Life Events
#+TAGS: personal
#+PERMALINK: /2022/07/19/Bhupinder-Singh/
#+COMMENTS: true

Bhupinder Singh, different voice, but power to go straight through your heart. I first heard about him when I might be in 4th or 5th grade and listened to song Naam Gum Jaayega on Chitrahaar. It instantly became my favorite song.

Dil Dhoondhta Hai was the song which I recognized was sung by him just by his voice. It was his second song that I listened. It was from the film Mausam.

The one song that I absolutely love is his duet with Sudesh Wadkar - Huzoor Is Kadar. A song that I first sang for Priti during our engagement. A song Gajendra and I have wanted to sing together for such a long time. Hopefully, one day! Bhupinder Singh gave us so many songs to cheer, cherish and remember him. Will miss him.

Bhupinder Singh ji your voice will continue to mesmerize us.

Om Shanti!
