#+TITLE: How to read a book
#+DESCRIPTION: Reading is fun and in this post I will share how I approach reading and reading alternatives
#+DATE: 2022-02-10
#+CATEGORIES: Books & Reading
#+TAGS: book-review
#+PERMALINK: /2022/02/10/how-to-read-a-book/
#+COMMENTS: true

I recently made a post on LinkedIn[fn:1][fn:2] on having read 72 books last year and few of the folks asked how I managed to do that.

I am a vociferous reader and there was a time when I could read 100s of books in a year. In this post I will share what works for me.

*** Motivation to Read
:PROPERTIES:
:CUSTOM_ID: motivation-to-read
:END:
Reading is more than the number of books you read in a year. We don't read because we are in a competition but because we want to enjoy, get clarity on certain things, gain knowledge or simply to entertain ourselves. You need to find your motivation. But don't just make it 'number of book read in a year.” Gamification sometimes is a great motivator but soon it becomes exhausting. Remember reading just one book a year is fine as long as you enjoyed reading it and it helped you with whatever you desired from it. In short there are more ways to enjoy the bliss of reading than just the numbers of books read.

*** Reading and Discipline
:PROPERTIES:
:CUSTOM_ID: reading-and-discipline
:END:
Reading itself requires discipline. Just like any other thing in life you need to set aside time for it. If you want to be healthy, you have to spend time on your body, if you want to improve your relationships you will need to spend time on it. Same with reading. What I do is I set some time on my calendar for reading. How much and how often will depend on your preferences. But putting time on calendar is important. I put one hour at night for reading just before I go to bed. It gives me good winding down time. For you it might be different - say 15 min a day or one hour on Sunday afternoon - whatever works for you.

*** Feel Empowered to Spend Time Wisely
:PROPERTIES:
:CUSTOM_ID: feel-empowered-to-spend-time-wisely
:END:
Though reading is a great habit but we must remember that not all books are made equal. That means you don't have to read all the books cover-to-cover. Sooner you realize this, better it will be for your reading confidence and help you maintain reading discipline. You get to decide which book you want to read, and also once start, whether you want to finish it or just shelve it. It is your time and you must feel empowered to use it wisely.

*** Reading Books
:PROPERTIES:
:CUSTOM_ID: reading-books
:END:
With things more settled, let's delve into how to read books.

We all know there are two kind of books - fiction and non-fiction. Non-fiction can be further divided into Textbooks, Autobiographies and Other (self-help books, etc.).

The method that I am going to discuss here is mostly for non-fiction books. For Fiction books, I tend to read them cover-to-cover, if they are interesting enough. If not, they just get marked read and shelved.

*** How to read non-fiction books?
:PROPERTIES:
:CUSTOM_ID: how-to-read-non-fiction-books
:END:
1) /Textbooks/: I only read chapters and sections that are relevant to the learning I am interested in. Nothing more, nothing less. Cookbooks, etc. should be similar.

2) /Autobiographies/: These are similar to fiction books and if the writing is interesting, I might read them cover to cover.

3) /Others/: This section will cover the method that will be more relevant to these kinds of books. I read books in passes, so sometimes you will see I mark the same book as read several times on GoodReads[fn:3]. These passes might not occur one after another. Again, I get to decide when and what I want to read. Let's talk more about passes:

*/Pass 1/*

For any book that you read, the first thing that you need to do is decide whether you want to read the book - whether you are ready to devote your time on the book. If not, you can exercise your power to shelve the book.

In this pass, I read the preface, the table of contents, front and back cover, index, etc. This gives me the idea on what the book is going to discuss. If it still interests me, I move on to Pass 2. Otherwise book is marked as read and shelved.

*/Pass 2/*

In this pass, I go a little further. If the book is divided into chapters, I read first paragraph from each chapter. If not, I just select few random paragraphs and read them. By this point, either I am intrigued to read more or I am totally bored. In any case, I have a good idea of what the author want to convey.

*/Pass 3/*

I read the book but do not use my brain to deeply understand or make counter-arguments in my mind. Even if I don't understand an argument or anything, I don't spend too much time on it. I simply move on.

After this pass, I am again at a decision point - do I want to understand this book and dig deeper. Most books don't go beyond Pass 3. But that is okay. Probably, they have satisfied my desired outcome and I have gathered all the information I needed.

*/Pass 4/*

This pass is the one which requires devotion to the book. I make notes, ponder about the arguments and form counter-arguments if at all possible. At this point, I am trying to have a conversation with the author, my superficial thoughts and my deep thoughts.

That's it. In most cases Pass 3 would be the most you will reach and like I said above that's okay. If you gained what you were interested in, that is more than sufficient.

*** Reading Alternatives
:PROPERTIES:
:CUSTOM_ID: reading-alternatives
:END:
If you can't read yourself, let someone else read it to you. Audio books are a great way to explore books and you can do it anywhere - even while driving. You can loan audiobooks from libraries. Most libraries have digital presence. Try the Libby app[4] and search for the library you have membership with.

Recently there are number of Apps that give you short summaries of the books. I would recommend them for non-fiction books other than autobiographies and textbooks. Apps like Blinkist[fn:4], Lucid[fn:5], StoryShots[fn:6], Get Abstract[fn:7] are few that I have tied in the past and they are great if you want to get a gist of a book like we discussed in Pass 1,2 and 3 above. This is also helpful before you decide to make a purchase.

*** Conclusion
:PROPERTIES:
:CUSTOM_ID: conclusion
:END:
So, as a parting thought I will reiterate that it is important to enjoy the activity you are doing. So, enjoy reading without overwhelming yourself with the number of books that you must read in a year. Also, you have power to not finish the book that you start. If the author is not able to grab your attention, it is their fault, not yours. Take reading as a medidative exercise, not something you must and have to do.

Also, this might or might not work for you. So, you will have to modify or develop totally new strategy for yourself. If you do so, please do share your insights.

Happy Reading!

/References/

[fn:1] Link to the post on [[https://www.linkedin.com/posts/systemhalted_reading-booksreadin2021-activity-6886145172648837120-PR9d][LinkedIn]]. I will cross-post it here one day.

[fn:2] If you are not connected with me on [[https://www.linkedin.com/in/systemhalted/][LinkedIn]]. Be sure to mention why do you want to connect with me.

[fn:3] If you are not already connected with me on GoodReads, please do. [[file:www.goodreads.com/systemhalted][Here is the link]]

[fn:4] [[https://www.blinkist.com][Blinkist App]]

[fn:5] [[https://lucid.fyi][Lucid App]]

[fn:6] [[https://www.getstoryshots.com][Story Shots App]]. They are currently running a Lifetime membership plan.

[fn:7] [[https://www.getabstract.com/en/][Get Abstract App]]. I think this has the most Enterprise Subscriptions.
